### ISSUE TITLE
Pls change license to MIT

### ISSUE THREAD

**Issue by edmand46** [kurozael/zapnet#1]
If I understood correctly, GNU v3, require opensource project where code is used, so if I create game with zapnet, I should open source it?

**Comment by kurozael** [comment]
@edmand46 all it means is that you need to make public any modifications you make to *Zapnet* itself which you can do as a fork here on GitHub. Your game doesn't need to be open-source, and you can quote me here 👍 

https://github.com/deadgg/zapnet/blob/main/LICENSE

You can use Zapnet in any commercial and/or private project.
